jobs:
    release:
        env:
            LIFERAY_RELEASE_GITHUB_PAT: ${{ secrets.LIFERAY_RELEASE_GITHUB_PAT }}
        if: (github.repository == 'liferay-release/liferay-docker')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ssh-key: ${{ secrets.SSH_PRIVATE_KEY_PORTAL_EE }}
                  repository: lucasmiranda0/portal-ee
            - name: Execute run_tests.sh
              run: ./run_tests.sh
              shell: bash
name: Release
on:
    pull_request:
        types: [opened, reopened]