name: Secrets and Environment Variables

on:
  pull_request:
    types: [opened, reopened]

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      MY_API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Tell me a secret!
        run: echo "My existing secret is ${{ secrets.API_KEY }}"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
         chmod +x .github/scripts/custom.sh
         .github/scripts/custom.sh
        shell: bash